name: Deploy to ECS Fargate

on:
  workflow_dispatch:

env:
  AWS_REGION: us-west-1  # Change to your region
  ECR_REPOSITORY: hclbayerpatientpareek
  ECS_CLUSTER: my-ecs-fargate-cluster
  ECS_SERVICE: patient-service
  TASK_DEF_NAME: patient-service-task

jobs:
  deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.6.6  # or latest you prefer

    - name: Terraform Init
      run: |
        cd terraformdeployment
        terraform init
        terraform apply -auto-approve

    - name: Force new ECS deployment
      run: |
        aws ecs update-service \
          --cluster $ECS_CLUSTER \
          --service $ECS_SERVICE \
          --force-new-deployment